export const THEMES = [
  {
    id: "canvas",
    name: "Canvas",
    description: "Quiet neutral cards and rounded controls.",
    navigation: "floating",
    taskLayout: "cards",
    settingsLayout: "split",
    controlStyle: "pill",
    mode: "light",
    colors: ["#f1f0ed", "#ffffff", "#474847", "#deded9"],
  },
  {
    id: "contrast",
    name: "Contrast",
    description: "Black and white with clear outlines.",
    navigation: "top",
    taskLayout: "rows",
    settingsLayout: "stacked",
    controlStyle: "outlined",
    mode: "light",
    colors: ["#ffffff", "#ffffff", "#151515", "#151515"],
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Warm paper, strong headings, quiet details.",
    navigation: "top",
    taskLayout: "editorial",
    settingsLayout: "columns",
    controlStyle: "underline",
    mode: "light",
    colors: ["#f6f2e9", "#fffdf7", "#7b382a", "#d8cebe"],
  },
  {
    id: "harbor",
    name: "Harbor",
    description: "Cool blue with navigation on the right.",
    navigation: "right",
    taskLayout: "rows",
    settingsLayout: "split",
    controlStyle: "rounded",
    mode: "light",
    colors: ["#eff4f8", "#ffffff", "#176188", "#cddce6"],
  },
  {
    id: "ledger",
    name: "Ledger",
    description: "Compact lists and neatly aligned fields.",
    navigation: "sidebar",
    taskLayout: "compact",
    settingsLayout: "rail",
    controlStyle: "square",
    mode: "light",
    colors: ["#f2f4f3", "#ffffff", "#315b4e", "#cbd4cf"],
  },
  {
    id: "atelier",
    name: "Atelier",
    description: "Warm panels and tasks arranged by status.",
    navigation: "floating",
    taskLayout: "board",
    settingsLayout: "columns",
    controlStyle: "rounded",
    mode: "light",
    colors: ["#f7f0e7", "#fffaf3", "#a44430", "#e3d1bd"],
  },
  {
    id: "orbit",
    name: "Orbit",
    description: "Dark violet with a slim navigation bar.",
    navigation: "rail",
    taskLayout: "cards",
    settingsLayout: "rail",
    controlStyle: "pill",
    mode: "dark",
    colors: ["#191625", "#242033", "#c0a7ff", "#48405d"],
  },
  {
    id: "deck",
    name: "Deck",
    description: "Blue task boards and navigation below.",
    navigation: "bottom",
    taskLayout: "board",
    settingsLayout: "stacked",
    controlStyle: "rounded",
    mode: "light",
    colors: ["#edf4fa", "#ffffff", "#1e6091", "#cfdfec"],
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Crisp blue outlines and structured rows.",
    navigation: "sidebar",
    taskLayout: "rows",
    settingsLayout: "columns",
    controlStyle: "outlined",
    mode: "light",
    colors: ["#edf3fa", "#ffffff", "#2059ad", "#b8cce7"],
  },
  {
    id: "garden",
    name: "Garden",
    description: "Green cards with room to breathe.",
    navigation: "right",
    taskLayout: "cards",
    settingsLayout: "split",
    controlStyle: "pill",
    mode: "light",
    colors: ["#edf3eb", "#fbfdf9", "#376537", "#cbdac4"],
  },
  {
    id: "gallery",
    name: "Gallery",
    description: "Wide cards, fine lines, a touch of plum.",
    navigation: "top",
    taskLayout: "cards",
    settingsLayout: "columns",
    controlStyle: "underline",
    mode: "light",
    colors: ["#f8f6f4", "#ffffff", "#78394d", "#ded7d6"],
  },
  {
    id: "signal",
    name: "Signal",
    description: "Dark green with compact task lists.",
    navigation: "rail",
    taskLayout: "compact",
    settingsLayout: "rail",
    controlStyle: "square",
    mode: "dark",
    colors: ["#111d1c", "#182927", "#80d6b5", "#385b53"],
  },
  {
    id: "mono",
    name: "Mono",
    description: "Neutral tones and a simple reading layout.",
    navigation: "sidebar",
    taskLayout: "editorial",
    settingsLayout: "stacked",
    controlStyle: "underline",
    mode: "light",
    colors: ["#f3f3f3", "#ffffff", "#333333", "#d0d0d0"],
  },
  {
    id: "notebook",
    name: "Notebook",
    description: "Cream paper, blue details, lined fields.",
    navigation: "sidebar",
    taskLayout: "rows",
    settingsLayout: "split",
    controlStyle: "underline",
    mode: "light",
    colors: ["#fbf7ed", "#fffdf7", "#385571", "#d8d2c1"],
  },
  {
    id: "workshop",
    name: "Workshop",
    description: "Warm grey with sturdy, square controls.",
    navigation: "top",
    taskLayout: "compact",
    settingsLayout: "columns",
    controlStyle: "square",
    mode: "light",
    colors: ["#f2eee9", "#ffffff", "#99501f", "#d5cbbc"],
  },
  {
    id: "focus",
    name: "Focus",
    description: "Quiet teal and a narrow reading layout.",
    navigation: "rail",
    taskLayout: "editorial",
    settingsLayout: "split",
    controlStyle: "rounded",
    mode: "light",
    colors: ["#f1f6f5", "#ffffff", "#245f62", "#d1e0dd"],
  },
  {
    id: "cinema",
    name: "Cinema",
    description: "Dark blue cards with soft pink details.",
    navigation: "bottom",
    taskLayout: "cards",
    settingsLayout: "rail",
    controlStyle: "pill",
    mode: "dark",
    colors: ["#141621", "#202333", "#ecb2cb", "#44485f"],
  },
  {
    id: "column",
    name: "Column",
    description: "Warm neutrals and a clean reading column.",
    navigation: "right",
    taskLayout: "editorial",
    settingsLayout: "stacked",
    controlStyle: "square",
    mode: "light",
    colors: ["#f4eee6", "#fffaf3", "#715139", "#d9ccba"],
  },
  {
    id: "mosaic",
    name: "Mosaic",
    description: "Violet outlines and grouped task boards.",
    navigation: "floating",
    taskLayout: "board",
    settingsLayout: "columns",
    controlStyle: "outlined",
    mode: "light",
    colors: ["#f3eff8", "#ffffff", "#6a439b", "#d8c9e9"],
  },
  {
    id: "metro",
    name: "Metro",
    description: "Dark slate, amber details, clear rows.",
    navigation: "top",
    taskLayout: "rows",
    settingsLayout: "rail",
    controlStyle: "square",
    mode: "dark",
    colors: ["#1a2027", "#252e38", "#f1bb80", "#475565"],
  },
] as const;

export type ThemeId = (typeof THEMES)[number]["id"];

export const DEFAULT_THEME: ThemeId = "canvas";

export function isTheme(value: unknown): value is ThemeId {
  return (
    typeof value === "string" && THEMES.some((theme) => theme.id === value)
  );
}
